## --- alacritty configuration --- ##
font:
  bold:
    family: monospace
    style: Bold
  bold_italic:
    family: monospace
    style: Bold Italic
  italic:
    family: monospace
    style: Italic
  normal:
    family: monospace
    style: Regular
  size: 10

window:
  padding:
    x: 2
    y: 2
  title: alacritty
  dynamic_padding: false
  gtk_theme_variant: None

scrolling:
  history: 10000

background_opacity: 0.80

cursor:
  style:
    shape: Block
      #blinking: On

mouse:
  hint:
    launcher:
      program: xdg-open
      args: []

colors:
  search:
    focused_match:
      foreground: '#181818'
      background: '#ab4642'
    matches:
      foreground: '#181818'
      background: '#f4bf75'
    bar:
      foreground: '#d0d0d0'
      background: '#262626'
  primary:
    background: '#000000'
    foreground: '#efebd9'

  # Normal colors
  normal:
    black:   '#191919'
    red:     '#b02626'
    green:   '#40a62f'
    yellow:  '#f2e635'
    blue:    '#4C4CFF'
    magenta: '#b30ad0'
    cyan:    '#32d0fc'
    white:   '#acadb1'

  # Bright colors
  bright:
    black:   '#36393d'
    red:     '#ce2727'
    green:   '#47c930'
    yellow:  '#fff138'
    blue:    '#2e4bea'
    magenta: '#cc15ed'
    cyan:    '#54d9ff'
    white:   '#dbdbdb'

  # Dim colors
  dim:
    black:   '#676f78'
    red:     '#b55454'
    green:   '#78a670'
    yellow:  '#faf380'
    blue:    '#707fd0'
    magenta: '#c583d0'
    cyan:    '#8adaf1'
    white:   '#e0e3e7'

  cursor:
    cursor: '#ffffff'

key_bindings:
  - {key: V, mods: Control|Shift, action: Paste}
  - {key: C, mods: Control|Shift, action: Copy}
  - {key: Equals, mods: Control, action: IncreaseFontSize}
  - {key: Minus, mods: Control, action: DecreaseFontSize}
  - {key: Key0, mods: Control, action: ResetFontSize}
