## --- alacritty configuration --- ##
font:
  bold:
    family: iosevka
    style: Bold
  bold_italic:
    family: iosevka
    style: Bold Italic
  italic:
    family: iosevka
    style: Italic
  normal:
    family: iosevka
    style: Regular
  size: 12

window:
  opacity: 1
  padding:
    x: 2
    y: 2
  title: alacritty
  dynamic_padding: false
  dynamic: true
  gtk_theme_variant: None
  dimensions:
    columns: 180
    lines: 40


scrolling:
  history: 10000

cursor:
  style:
    shape: Block

mouse:
  hint:
    launcher:
      program: xdg-open
      args: []

colors:
  # Default colors
  primary:
    background: '0x151515'
    foreground: '0xd7d0c7'

  # Normal colors
  normal:
    black:   '0x101010'
    red:     '0xe84f4f'
    green:   '0xb8d68c'
    yellow:  '0xe1aa5d'
    blue:    '0x7dc1cf'
    magenta: '0x9b64fb'
    cyan:    '0x6d878d'
    white:   '0xdddddd'

  # Bright colors
  bright:
    black:   '0x404040'
    red:     '0xd23d3d'
    green:   '0xa0cf5d'
    yellow:  '0xf39d21'
    blue:    '0x4e9fb1'
    magenta: '0x8542ff'
    cyan:    '0x42717b'
    white:   '0xdddddd'

key_bindings:
  - {key: V, mods: Control|Shift, action: Paste}
  - {key: C, mods: Control|Shift, action: Copy}
  - {key: K, mods: Control|Shift, action: IncreaseFontSize}
  - {key: J, mods: Control|Shift, action: DecreaseFontSize}
  - {key: Key0, mods: Control, action: ResetFontSize}
