[colors.bright]
black = "0x404040"
blue = "0x4e9fb1"
cyan = "0x42717b"
green = "0xa0cf5d"
magenta = "0x8542ff"
red = "0xd23d3d"
white = "0xdddddd"
yellow = "0xf39d21"

[colors.normal]
black = "0x101010"
blue = "0x7dc1cf"
cyan = "0x6d878d"
green = "0xb8d68c"
magenta = "0x9b64fb"
red = "0xe84f4f"
white = "0xdddddd"
yellow = "0xe1aa5d"

[colors.primary]
background = "#121212"
#background = "#1e1e1e"
foreground = "0xd7d0c7"

[cursor.style]
shape = "Block"

[font]
size = 11

[font.bold]
family = "iosevka"
style = "Bold"

[font.bold_italic]
family = "iosevka"
style = "Bold Italic"

[font.italic]
family = "iosevka"
style = "Italic"

[font.normal]
family = "iosevka"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[scrolling]
history = 10000

[window]
dynamic_padding = true
opacity = 1.0

[window.dimensions]
columns = 170
lines = 45
