[colors.primary]
background = "#111111"
foreground = "#ffffff"

[colors.normal]
black = "0x101010"
blue = "0x7dc1cf"
cyan = "0x6d878d"
green = "0xb8d68c"
magenta = "0x9b64fb"
red = "0xe84f4f"
white = "0xdddddd"
yellow = "0xe1aa5d"

#black =   "#000000"
#red =     "#cc0403"
#green =   "#19cb00"
#yellow =  "#cecb00"
#blue =    "#0d73cc"
#magenta = "#cb1ed1"
#cyan =    "#0dcdcd"
#white =   "#dddddd"

[colors.bright]
black = "0x404040"
blue = "0x4e9fb1"
cyan = "0x42717b"
green = "0xa0cf5d"
magenta = "0x8542ff"
red = "0xd23d3d"
white = "0xdddddd"
yellow = "0xf39d21"

#[colors.bright]
#black = "#767676"
#red = "#f2201f"
#green = "#23fd00"
#yellow = "#fffd00"
#blue = "#1a8fff"
#magenta = "#fd28ff"
#cyan = "#14ffff"
#white = "#ffffff"

[cursor.style]
shape = "Block"

[font]
size = 10.0

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.bold_italic]
family = "Iosevka Term"
style = "Bold Italic"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[scrolling]
history = 10000

[window]
dynamic_padding = true
opacity = 1.0
padding = { x = 1, y = 1 }

[window.dimensions]
columns = 140
lines = 35
