"   __   _(_)_ __ ___  _ __ ___
"   \ \ / / | '_ ` _ \| '__/ __|
"    \ V /| | | | | | | | | (__
"     \_/ |_|_| |_| |_|_|  \___|

" --- parameters
syntax on
set nowrap
set showcmd
set nobackup
set undofile
set t_Co=256
set incsearch
set smartcase
set expandtab
set tabstop=4
set noswapfile
set ignorecase
set smartindent
set nocompatible
set noerrorbells
set shiftwidth=4
set foldcolumn=0
set termguicolors
set updatetime=50
set encoding=UTF-8
filetype plugin on
set complete+=kspell
set formatoptions-=cro
set number relativenumber
set undodir=~/.vim/undodir
set wildmode=longest,list,full
set completeopt=menuone,longest
set previewpopup=height:15,width:60
set viminfo='100,n$HOME/.vim/files/info/viminfo
let mapleader = " "

" local filetype settings
autocmd FileType tex setlocal wrap tw=100
autocmd FileType markdown setlocal wrap tw=100
autocmd FileType vimwiki setlocal wrap tw=100

autocmd BufWritePre * %s/\s\+$//e
autocmd InsertEnter,InsertLeave * set cursorline!
autocmd InsertEnter,InsertLeave * set cursorcolumn!

" auto place cursor where it was last when opening a file
if has("autocmd")
        au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
			\| exe "normal! g'\"" | endif
endif

" auto save and load folds
augroup remember_folds
  autocmd!
  autocmd BufWinLeave * mkview
  autocmd BufWinEnter * silent! loadview
augroup END

" --- plug in manager (vim-plug)
call plug#begin('~/.vim/autoload')

Plug 'junegunn/fzf.vim'
Plug 'vimwiki/vimwiki'
Plug 'preservim/nerdcommenter'

Plug 'jiangmiao/auto-pairs'
Plug 'alvan/vim-closetag'
"Plug 'dense-analysis/ale'
Plug 'vim-scripts/AutoComplPop'
Plug 'airblade/vim-gitgutter'

Plug 'itchyny/lightline.vim'
Plug 'nanotech/jellybeans.vim'
Plug 'tomasiser/vim-code-dark'
Plug 'ap/vim-css-color'

call plug#end()

" --- colorscheme
colorscheme jellybeans

" --- keybindings
map cc :!
map fj 0cw<bs><cr><esc>
map <leader>t :tabe<CR>
map <leader>n :tabn<CR>
map <leader>n :Lexplore<CR>
map <leader>. :Files ~/<CR>
map <leader>> :History<CR>
noremap <leader>] :wincmd <<CR>
noremap <leader>[ :wincmd ><CR>
map <leader>b :VimwikiUISelect<CR>
map <leader>g :GitGutterToggle<CR>
map <leader>r :%s///g<Left><Left><Left>

" --- netrw
let g:netrw_altv=1
let g:netrw_banner=0
let g:netrw_winsize=15
let g:netrw_liststyle=3
let g:netrw_browse_split=4

augroup AutoDeleteNetrwHiddenBuffers
    au!
    au FileType netrw setlocal bufhidden=wipe
augroup end

" --- Vimwiki
let wiki_1 = {}
let wiki_1.auto_diary_index = 1
let wiki_1.path = '~/doc/vimwiki/'
let wiki_1.path_html = '~/doc/vimwiki/html_doc/'

let g:vimwiki_list = [wiki_1]

" --- lightline
set laststatus=2
set noshowmode
let g:lightline = {
      \ 'colorscheme': 'jellybeans',
      \ 'active': {
      \     'left': [ [ 'mode', 'paste' ],
      \               [ 'gitbranch', 'readonly', 'filename', 'modified' ] ],
      \     'right': [ [ 'lineinfo' ],
      \              [ 'percent' , 'filetype'] ]
      \ }
      \ }

" --- fzf
let g:fzf_layout = { 'down':  '20%'}
