#!/bin/sh
bspc rule -r "*"

## --- autostart --- ##
killall sxhkd
killall picom
killall polybar
sxhkd &
picom -b &
nitrogen --restore
sh ~/.config/polybar/launch.sh

## --- moniters --- ##
bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9'

## --- perameters --- ##
bspc config border_width 2
bspc config window_gap 16
bspc config top_padding 45 # top_padding set equal to polybar height and dmenu height
bspc config split_ratio 0.50

bspc config normal_border_color "#181818"
bspc config active_border_color "#ffffff"
bspc config focused_border_color "#89CFF0"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

bspc config focus_follows_pointer true
bspc config initial_polarity first_child
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

## --- rules --- ##
bspc rule -a Zathura state=tiled
bspc rule -a Sxiv state=tiled
