#!/bin/sh

# Print the status of battery 0 or the internal battery
bat0=$(cat /sys/class/power_supply/BAT0/status)
case $bat0 in
	Full)
		echo "0: $(cat /sys/class/power_supply/BAT0/capacity | sed 's/$/%/')"
	;;	
	Unknown)
		echo "0: $(cat /sys/class/power_supply/BAT0/capacity | sed 's/$/%/')"
	;;
	Discharging)
		echo "0: $(cat /sys/class/power_supply/BAT0/capacity | sed 's/$/%/') Dis"
	;;
	Charging)
		echo "0: $(cat /sys/class/power_supply/BAT0/capacity | sed 's/$/%/') Char"
	;;
esac
