#!/bin/sh

# Print the status of battery 1 or the external battery
bat1=$(cat /sys/class/power_supply/BAT1/status) 
case $bat1 in
	Full)
		echo "1: $(cat /sys/class/power_supply/BAT1/capacity | sed 's/$/%/')"
	;;
	Unknown)
                echo "1: $(cat /sys/class/power_supply/BAT1/capacity | sed 's/$/%/')"
	;;
	Discharging)
		echo "1: $(cat /sys/class/power_supply/BAT1/capacity | sed 's/$/%/') Dis"
	;;
	Charging)
		echo "1: $(cat /sys/class/power_supply/BAT1/capacity | sed 's/$/%/') Char"
	;;
esac
