#!/bin/sh

# input volume
if [[ $(amixer sget Capture | grep 'Left:' | awk -F '[][]' '{ print $4 }') = "on" ]]; then
	echo "in: $(amixer sget Capture | grep 'Left:' | awk -F '[][]' '{ print $2, $4 }')"
else
	echo 
fi

 
