#!/bin/sh

again=true
while $again == true
do
    option1=$(ls -a | dmenu -l 10 -i -p "drag-drop:")
    option2=$(echo -e "change-directory\nlink\nread\nquit" | dmenu -l 4 -i -p "choice:")
    case $option2 in
        link)
            dragon $option1
        ;;
        read)
            $READER $option1
        ;;
        change-directory)
            cd $option1
        ;;
        quit)
            again=false
        ;;
    esac
done
